export const OPEN_NOTIFICATIONS_MODAL = 'OPEN_NOTIFICATIONS_MODAL';
export type OPEN_NOTIFICATIONS_MODAL = typeof OPEN_NOTIFICATIONS_MODAL;


export const CLOSE_NOTIFICATIONS_MODAL = 'CLOSE_NOTIFICATIONS_MODAL';
export type CLOSE_NOTIFICATIONS_MODAL = typeof CLOSE_NOTIFICATIONS_MODAL;