export const OPEN_NOTIFICATIONS_MODAL = 'OPEN_NOTIFICATIONS_MODAL';
export type OPEN_NOTIFICATIONS_MODAL = typeof OPEN_NOTIFICATIONS_MODAL;

export const CLOSE_NOTIFICATIONS_MODAL = 'CLOSE_NOTIFICATIONS_MODAL';
export type CLOSE_NOTIFICATIONS_MODAL = typeof CLOSE_NOTIFICATIONS_MODAL;

export const SET_SNOOZE_UNTIL = 'SET_SNOOZE_UNTIL';
export type SET_SNOOZE_UNTIL = typeof SET_SNOOZE_UNTIL;

export const END_SNOOZE = 'END_SNOOZE';
export type END_SNOOZE = typeof END_SNOOZE;